### ISSUE TITLE
can not set icon

### ISSUE THREAD

**Issue by WingDust** [kweatherman/Folcolor#1]
![image](https://user-images.githubusercontent.com/45911286/112411036-31140980-8d57-11eb-88b9-68559c5810d4.png)

**Comment by WingDust** [comment]
stystem can not find path

**Comment by kweatherman** [comment]
All language file paths should work now:
![language_folders_sample](https://user-images.githubusercontent.com/76711484/118380629-33555000-b5b1-11eb-952b-858871c76066.png)

Please use the [latest release](https://github.com/kweatherman/Folcolor/releases).
