### ISSUE TITLE
can you allow me to change the folder colors without modifying the date.  preserve original date and time

### ISSUE THREAD

**Issue by Zedroid** [kweatherman/Folcolor#11]
can you allow me to change the folder colors without modifying the date

https://www.nirsoft.net/utils/bulk_file_changer.html lets me edit the date and timestamp
adding tags seem to make the file the newest like in folcolor

robocopy can create a temp folder with original attributes before overwrite
https://answers.microsoft.com/en-us/windows/forum/all/retaining-the-original-date-modified-of-folders/0c0982f9-03a5-47f6-ae32-f2691d647889

**Comment by kweatherman** [comment]
I see yea, interesting, never realized that was happening.
Even if the color is changed the modification date of the "desktop.ini" inside the folder doesn't change but the folder itself does.

**Why and when is a problem though? What is the specific use case(s) where it is necessary to not change the folder date?**

Would need to investigate what API call(s) in Folcolor causes the date to change. At any rate would probably have to push and pop the date to make it work right.

Do you realize you can change the date from a batch file?  
This line will save the current date:  
`set todaysdate=%date:~-10%`  
Then I will set it back to last year:  
`date 01/31/2022`  
.. do something here..  
Then pop it back:  
`date %todaysdate%`  
But then this is the date, not the time too. Maybe is there a DOS command for it also.

**Comment by Zedroid** [comment]
Thank you for that useful hack! I did not know it might be useful someday.  Unfortunately I wanted to preserve the order of YouTube videos I downloaded in case I want to re-watch, but track which ones I already watched.

**Comment by kweatherman** [comment]
I see. Yea, I hate little annoying things like that. I think I just gave up trying to track dates like this because of it some time ago.

Maybe you can just date your folders like "Downloads 1_31_2023" or something.

Anyhow, I don't think this is something I want to spend energy on.
If you want it done you are probably going to have to make a fork and add the feature yourself.

**Comment by Zedroid** [comment]
Thank you for the reply. That is a good tip.  I understand it's fine I'll fork it only as a reference in the future since I'm no software developer.   Thank you for your time creating this software by the way.
