### ISSUE TITLE
Feature request - Ability to color "Quick Access" folders

### ISSUE THREAD

**Issue by meikemeisje** [kweatherman/Folcolor#12]
Hi,
I just downloaded your app and I love it! I was wondering if it would be possible for the folder colors to also show up in Windows (10, in this case) Explorer's "Quick Access" bar? That would be super helpful for me :) 
Kind regards,
Meike

**Comment by kweatherman** [comment]
Thanks, appreciate it.

So you mean this quick view right?
![image](https://github.com/kweatherman/Folcolor/assets/76711484/754dac0f-7894-47d8-b1f3-761cb456aef3)

If not, show a better screenshot please.

**Comment by meikemeisje** [comment]
Hey! No, I mean this here :)
![image](https://github.com/kweatherman/Folcolor/assets/133099082/6abe6109-dd82-4965-9ef6-a0ea633e9c1f)

**Comment by kweatherman** [comment]
Okay, never really used the feature frankly. But now that I play with Quick Access (QA) maybe I will use it more.
Anyhow, what happens if you color the equivalent to the "Citizen" folder in the example?
I just pined a Folcolor'ed color folder for QA and it is indeed colored there for me.

Rebooting..

**Comment by meikemeisje** [comment]
oh that's interesting! I had colored two folders in the Quick Access where the color didn't show up, then I unpinned one and re-pinned it; the color showed up, and it also showed up for the other folder 😅 so that's a loophole that works 😉

**Comment by kweatherman** [comment]
Please do that for now. It would be nicer to right click set color on it, etc., but it will take me some research how the OS does it.
