### ISSUE TITLE
[Feature request] Add support for Windows 11 context menu

### ISSUE THREAD

**Issue by scarneros** [kweatherman/Folcolor#13]
Currently, you have to click "Show more options" to show the old context menu where the Color Folder options are, or right click the folder while pressing "Shift" to invoke the old context menu.

https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

**Comment by kweatherman** [comment]
From this new Windows 11 context menu change?
I ask because I don't use 11 and would have to fire up a Windows 11 VM and update it to see the change.

**Comment by abirpahlwan** [comment]
![image](https://github.com/kweatherman/Folcolor/assets/15526620/bf69bc4a-1af5-4ab3-b1cc-8a468b80a292)

![image](https://github.com/kweatherman/Folcolor/assets/15526620/a6ab9540-110f-4401-8bc6-8c8299beb00e)

**Comment by bancalero** [comment]
Came here to request the same thing

The extra step clicking "show more options" become a little annoying after some time, so a native entry in the new context menu would be a really cool addition :)

Thx for the work!

**Comment by abirpahlwan** [comment]
casual bump

**Comment by kweatherman** [comment]
I researched it a bit. It looks like there is no normal route around this. 
Maybe using an explorer extension which I didn't want to do once I realized this thing could be done using the shell registry.
If you see an example of some other tool bypassing the "Show more options" sub-menu let me know.

What you can do is though is just turn off this feature entirely in Windows 11 to have the "long" options back again like in Windows 10.
See:
https://www.ubackup.com/windows-11/windows-11-always-show-more-options-right-click-jkzbj.html
https://www.elevenforum.com/t/disable-show-more-options-context-menu-in-windows-11.1589/
etc.

**Comment by kweatherman** [comment]
Update. Okay now that I have been actually using Windows 11, the easiest thing is to just hold now the SHIFT key.
SHIFT-Right click will bring up the context options like Windows 10.
