### ISSUE TITLE
Question: Does it need to run in the background or does it trigger some windows internal tweaks/registry entries ? 

### ISSUE THREAD

**Issue by Ulf3000** [kweatherman/Folcolor#14]
what the title says. 

does this program run in the background and hook explorer.exe or something ?

**Comment by kweatherman** [comment]
No not at all. It just uses the Explorer shell menu entries.
The only time the executable runs is when you right click to set a color, etc.
Plus I made the executable to do only the minimal to set up a folder to show a folder icon, with the icon resource being the same executable.
