### ISSUE TITLE
just doesn't work... but it did before!

### ISSUE THREAD

**Issue by hotwiredis** [kweatherman/Folcolor#16]
using the right click menu, i select a color and.... nothing. folder color doesn't change. I've restarted, removed antivirus, uninstalled and reinstalled folcolor, and it just won't work. UAC is set to the absolute lowest.

weirdly enough, when i installed this for the first time yesterday it was working great, i was enjoying the hell out of it but now it just won't work. very confused. this issue is happening on my local pc and on the network drive, nowhere allows me to change colors anymore.

**Comment by kweatherman** [comment]
Strange okay. I don't think this is a common problem since your are the only person reporting this currently.
Although someone mentioned a problem with network drives recently. And I just built a new Windows 10 system and put Folcolor on it with no problems.

Do you have some antivirus software or something that might have removed the registry settings?

Try uninstalling Folcolor, then installing it back again. It should restore the registry settings, etc.

**Comment by hotwiredis** [comment]
I've tried reinstalling folcolor 4 times now, and so far have noticed a slight success. i can now change folder colors on my local PC, however it still doesn't do anything on the network drive. keep in mind, the 'network drive' is just a network-accessible hdd on my other windows 10 PC, which i also installed folcolor on to see if that would help resolve the issue. still no luck.

**Comment by kweatherman** [comment]
Ahh okay, I think this is the same as this #15 that was recently reported.
I'll have to investigate why it doesn't apply to mapped drives. 
Please read that issue and look at his solution (albeit tedious) as a temporary one for now.

**Comment by hotwiredis** [comment]
his mapped drive was in Linux, whereas mine is windows. also, this DID work for a period of about 5 hours, so i think there's likely something else at play here given the fact it worked initially... strange indeed.

**Comment by hotwiredis** [comment]
So, it just started working again this morning. didn't change a thing, didn't even restart the computers. I don't want you to go chasing ghosts, so ill close this issue, but thank you for your time and responses!

**Comment by kweatherman** [comment]
Strange okay. If anything I'd think it's a rights issue. The right to create files (the "desktop.ini" special normally hidden files) and set the file as "system".
So it must become network rights vs just local rights.

I don't doubt you or the other user have/had the problem.
I have yet to setup for it.

I wonder it could be a Windows update thing.
Did you get a Windows update recently? It could have been a change that was introduced in one last month, then a new update might have fixed it. One possibility anyhow.
