### ISSUE TITLE
Unable to sort by colors

### ISSUE THREAD

**Issue by albert8899** [kweatherman/Folcolor#18]
Unable to sort folders by colors, which would be essential helpful.

**Comment by kweatherman** [comment]
Interesting, I see that is actually an option in the Explorer columns for "color".
I don't see how to set this criteria to "desktop.ini" files. If there is a way, I can't find any documentation about it.
Might take a Explorer shell extension, not sure.
I see one of the commercial folder options lets you sort by "Tags" which they have named with colors.
