### ISSUE TITLE
[Request] Show preview thumbnails and paper sheet inside the icon 

### ISSUE THREAD

**Issue by emvaized** [kweatherman/Folcolor#19]
Hi there! 
Would it be possible to show thumbnails of files inside the folder on the icon, like the default folder icon? When I set folder color, thumbnails are gone and folder icon is no longer "half-open":

![thumbnails](https://github.com/kweatherman/Folcolor/assets/37851576/b275d6e7-22f7-47c4-9862-055677342f96)

Another question — default folder icons change depening on whether folder is empty or not (paper sheet visible in the top left corner when folder is not empty): 
![изображение](https://github.com/kweatherman/Folcolor/assets/37851576/0cf3a567-e64b-4f2b-bcaa-1abcd5b8591d) 

Would it be possible to recreate this feature as well? 
I guess it just requires adding more supported icons in the set? For example, "folder with paper" (non empty) seems to be just another icon in the `SHELL32` file.

Thanks!

**Comment by kweatherman** [comment]
I see what you are talking about. 
Frankly I most always use the "details" view so I haven't experienced this enough to notice.
Apparently setting a a custom icon with "desktop.ini" breaks a lot of these behaviors.
Must be some logic in Explorer that switches the states according to like you show if it sees an icon like the Cyberpunk one, or like you say when it sees if a folder is empty or not.

And right probably another set of the icons with a "paper" in the file. Got to be some logic to these things.
If there is a way to fix these problems, I doubt it is just going to be the "desktop.ini" file way.
There is no active code that runs with Folcolor, only the small amount of code is run when a folder color is set or unset.

Also even if there is a "desktop.ini" way, like there is an additional "IconResourceEmpty" or just expanding the existing "IconResource" with some kind of index system I've never seen it documented. There is little documentation on the "desktop.ini" file options at all.

If you want to do some leg work, see if you can find another folder coloring utility that supports those options. Like try a few of the commercial offerings and see if these behaviors are fixed.
