### ISSUE TITLE
[Minor request] ability to change folder styles of different Windows versions?

### ISSUE THREAD

**Issue by TheInsane101** [kweatherman/Folcolor#21]
HI, I love that this program exists, thank you for that! However, I am currently not using it because I have a Windows 7 icon pack applied to my Windows 10 setup, and Windows 7's folder icons are slightly different in appearance. When the program changes the colour of a folder with the Windows 7 look, it also changes it back to the Windows 10 style and shape, causing some visual inconsistency.

(Note: this is real Windows 10's native explorer heavily customised, and while it's not using the original 7 icon pack at the moment, the point is to show that the style is reverted to stock 10 when changing the colour).
![image](https://github.com/kweatherman/Folcolor/assets/104862146/63644705-f93e-4485-b8a1-755a810298ef)

I am one of the few people who likes to customise the appearance of Windows, and I understand that this is very niche and a very minor inconvenience, but it would be nice if, for instance, there was a way to get Folcolor to let you choose which Windows version's style of folders to use, seeing as this program supports real Windows 7 as well. Maybe there could be an unofficial way to spoof the Windows version, so that the program thinks that I'm using 7 and thus gives me 7's options?

I'm not asking for the program to support ANY folder icon pack I apply, as that would require completely overhauling how this program even works in the first place; I was just wondering if I could just use the folder style of any existing version of Windows. Pretty much all icon packs out there follow the native folder style anyways (they never go for a custom folder shape etc), so this change would maintain consistency with those packs too.

Again, I understand this is a very niche ask, so I understand if you feel it isn't worth the time or effort to accommodate this, in which case, that's fine. Thank you for reading this anyways!

**Comment by kweatherman** [comment]
Since the exe (acts as a ICON resource as well) has a Windows 7 icon set already you could hack it to get it to work.
Where in the code it detects if Win 10, 7, etc., force it to always be Windows 7.

But for your existing icons set with Folcolor the indexes "desktop.ini" will be wrong.
You could probably make a Python script to reclusively fix them (offset them to the Win 7 indexes).

But you will have to do these things yourself.
