### ISSUE TITLE
Win 11 contextual menu

### ISSUE THREAD

**Issue by JasonGosling** [kweatherman/Folcolor#22]
Hey there, thanks for your work on this tool. Is there a way to get folcolor to function on the first page of the Win 11 contextual menu? Without going to _show more options_ first? Thanks in advance and apologies if you get asked this a lot.

**Comment by kweatherman** [comment]
See #13 
AFAIK the without making an Explorer shell extension to override the Win 11 behavior, the best way is probably use that setting in the thread to make it Win 10 style.

**Comment by kweatherman** [comment]
Update. Okay now that I have been actually using Windows 11, the easiest thing is to just hold now the SHIFT key.
SHIFT-Right click will bring up the context options like Windows 10.
