### ISSUE TITLE
[Request] Can it support one-time operations on multiple folders?

### ISSUE THREAD

**Issue by met-tk** [kweatherman/Folcolor#24]
Is it possible to select multiple folders at once and then right-click to change their colors?
I’ve tried it, but currently, it seems you can only change the color one folder at a time.
Thank you for creating such a great piece of software.

**Comment by kweatherman** [comment]
Try it again. I can with Windows 10. It's just that you will get the UAC dialog each time.
As I mentioned in previous solutions for the UAC box, you can temporarily turn it off by using the lowest selection.
But you probably shouldn't leave it off, else you won't get notifications when apps are trying to run as administrator.

**Comment by kweatherman** [comment]
Closed due to lack of response from OP.
