### ISSUE TITLE
Add Custom Icon (icl, zip)

### ISSUE THREAD

**Issue by Flavien06** [kweatherman/Folcolor#4]
Hello
It is possible to add custom .icl or .zip with ico file?
I want to add a windows 11 icon folder theme
Thank

**Comment by kweatherman** [comment]
The way Folcolor is that's it's icons are in an embedded resource. The executable part works as a utility to create a "desktop.ini" setup to show a folder icon.

Sounds like what you need is at the system level. Like changing the global icon set.
Folcolor doesn't do any of that, you'll have to look elsewhere for software that does this.

**Comment by Flavien06** [comment]
OK, too bad.
I have seen software like Folder Marker or Folderico which allows you to add additional icons or colors.  I think it saves the .ico in the folder to customise.
