### ISSUE TITLE
Add support for Windows 11

### ISSUE THREAD

**Issue by abirpahlwan** [kweatherman/Folcolor#7]
In Windows 11, old icons look out of place.
![Screenshot 2022-09-11 222613](https://user-images.githubusercontent.com/15526620/189538437-0d63d5df-a706-4785-a9ef-e75c6072dc10.jpg)

Can you add support for Windows 11, please?

**Comment by kweatherman** [comment]
Right okay, a new/different icon set.
I'll have to add support for it.

**Comment by kweatherman** [comment]
Give the 1.2.0 [release](https://github.com/kweatherman/Folcolor/releases) a shot.

**Comment by abirpahlwan** [comment]
checking it out

**Comment by abirpahlwan** [comment]
Works like a charm. Thanks a bunch 😄 
![Videos](https://user-images.githubusercontent.com/15526620/192028728-7889e261-5520-43d1-a466-910e9cd096b8.png)
