### ISSUE TITLE
Feature Request - Custom Colors

### ISSUE THREAD

**Issue by JessieBuchanan** [kweatherman/Folcolor#9]
HI, like you I was really disappointed that windows doesn't have a built in color picker, and was really glad someone had come along and made an open source variant. Simple and Elegant thank you. 

Do you think you could add a simple editor to change the colors we can select from? or maybe a dialog box for a RGG or HEX code?

**Comment by kweatherman** [comment]
Thanks.
You are not the first person to ask. But I don't plan on doing anything like that anytime soon.
It's more of a user interface thing then anything. And then the icons would have to be saved, probably one at the time then use serialized filenames or something.

Actually, maybe you or someone could just make a version of a folder colorizer in Python.
Can be setup just like I do using the registry shell entry.
Could PyQT use, etc. for the UI, to make it easier.
